### ISSUE TITLE
Mod Compatibility/Suggestion/Request

### ISSUE THREAD

**Issue by ghost** [CreativeMD/OpticManager#1]
You add day & night time configuration, it is perfect. But now i need to change also season time configuration in Tough As Nails Mod. It got a so longer or shorter time if i change day & night time. So it will not be sensible. **Can you add an option to change the season time (or day, whatever it is) in Tough As Nails mod as the day & night time configuration please?** Thank you.

**Comment by CreativeMD** [comment]
This has nothing to do with OpticManager itself. It's a request to add support for IGCM. Unfortunately, i  don't have much time left, sorry :(
