### ISSUE TITLE
Crash ingame config menu with latest creativecore 1.9.19

### ISSUE THREAD

**Issue by CcytherR** [CreativeMD/OpticManager#10]
When you press v to load up the config menu click opticmanager and nothing happens just crashes the game 1.12 issue is with creativeCore 1.9.19 reverted to last working version 1.9.18 works fine then.

**Comment by CreativeMD** [comment]
Can you send me the crash-report?

**Comment by CcytherR** [comment]
https://pastebin.com/gn1dB2fX crash report sorry late cause i forgot to reply

**Comment by CreativeMD** [comment]
Please use the pre3 instead, it should fix your issue.

**Comment by CcytherR** [comment]
Already tried that and a few other ways, https://pastebin.com/JYFpj678 same crash, like i said i could already get around the issue, i just revert to creative core 1.9.18 solves it at least till a situation where i have to use the latest creative core, more of a heads up anyway.

Thanks.

**Comment by CreativeMD** [comment]
OK, i will try to fix it soon. Thanks for reporting this issue.

**Comment by CreativeMD** [comment]
Issue should be fixed now (uploaded an updated version).
