### ISSUE TITLE
Hardcore Darkness moonlight compatibility issue

### ISSUE THREAD

**Issue by Aphyxia** [CreativeMD/OpticManager#11]
When both this mod and hardcore darkness are installed, OpticManager always overwrites the moonlight values set by hardcore darkness. I only use OpticManager for day and night lengths so if at all possible I'd like to be able to disable the light features of the mod entirely.

Using the latest version of all mods.

**Comment by CreativeMD** [comment]
Added an option to do so and uploaded it to curseforge. Should be available soon. Sorry for not responding earlier. Hope everything works fine now.
