### ISSUE TITLE
Total world time changes cause issues with other mods

### ISSUE THREAD

**Issue by rubensworks** [CreativeMD/OpticManager#13]
As reported in https://github.com/CyclopsMC/EverlastingAbilities/issues/166, this mod causes problems with Everlasting Abilities.

It looks this you are [changing the total world time](https://github.com/CreativeMD/OpticManager/blob/1.12/src/main/java/com/creativemd/opticmanager/OpticEventHandler.java#L96), while this is a value that should not be touched by anything other than MC's internal counter AFAIK.
Mods such as Everlasting Abilities depend on this counter to periodically execute tasks. If this value is changed externally, other mods can generate unexpected behaviour.

**Comment by CreativeMD** [comment]
I will try to upload a fix for it soon. Very confused as to why I set the world total time anyway.

**Comment by CreativeMD** [comment]
Really sorry that it took me so freaking long. The newest version should fix it and be available soon. If this issue still persists make sure to tell me so here and I will reopen this issue!
