### ISSUE TITLE
Crash with fabric 1.19.2

### ISSUE THREAD

**Issue by firyy** [CreativeMD/OpticManager#16]
Mixin missing
OpticManager-v1.3.1
CreativeCore latest and also tried with v2.7.4

[main/ERROR]: Mixin prepare for mod opticmanager failed preparing EntityRendererMixin in opticmanager.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'team.creative.opticmanager.mixin.EntityRendererMixin' was not found

**Comment by CreativeMD** [comment]
Can you send the entire crash-report? This is not enough to help out.

**Comment by CreativeMD** [comment]
Make sure to get the versions from curseforge and it should work just fine.

**Comment by firyy** [comment]
> Can you send the entire crash-report? This is not enough to help out.

Here it is

[https://pastebin.com/eLC5UbvE](url)
