### ISSUE TITLE
Galacticraft Uncompatibility

### ISSUE THREAD

**Issue by ghost** [CreativeMD/OpticManager#3]
i tweaked day tick length (per by day and night) and it's always day in other planets in Galacticraft, can you add a dimension filter for that feature? thanks.
using forge 2299, GC b91, latest optic manager & IGCM

**Comment by ghost** [comment]
please see this: (i recorded right now)
https://youtu.be/PKuR3YAczOY
can't add time, it's being crazy. and all works fine without optic manager, please help it. thanks.

**Comment by CreativeMD** [comment]
Does this fixes it?
https://www.dropbox.com/s/m3112g2xx7li1jr/OpticManager%20v1.1.2%20mc1.11.2.jar?dl=1

**Comment by ghost** [comment]
let me try.

**Comment by ghost** [comment]
uhm, should i delete my old saved config for opticmanager?

**Comment by CreativeMD** [comment]
No, actually it looks like this is just a client side issue, because i already limited on server side.

**Comment by ghost** [comment]
yes! it works awesome. thank you so much.

**Comment by ghost** [comment]
btw, can you add support for galacticraft in enhanced visuals? for example in the rocket, or in the moon, or in space, etc :D there are many ways. if u have a creative mind you will know what you can do :D i just want enhanced visuals mod adds content for Galacticraft. it would be cool. thanks again!

**Comment by CreativeMD** [comment]
Hm, honestly I think some more sound effects for AmbientSounds in space would have a larger immersive effect.

**Comment by ghost** [comment]
you know what you should add, i don't give suggestion :)

**Comment by ghost** [comment]
hey ah, it(youtube video) happens again in OVERWORLD this time. :(

**Comment by ghost** [comment]
using optic manager 1.1.2

**Comment by ghost** [comment]
and yeah it's a client issue i think, because it's day and i see mobs around, and most of the time i don't see mobs on day.

**Comment by CreativeMD** [comment]
This time it's the server. Sorry forgot a little thing. This should fixes it:
https://www.dropbox.com/s/tbdn7cwhwx7sica/OpticManager%20v1.1.3%20mc1.11.2.jar?dl=1

**Comment by ghost** [comment]
thanks...

**Comment by ghost** [comment]
you will upload the same jar to the curse, right? :D

**Comment by CreativeMD** [comment]
Yes of course :D
