### ISSUE TITLE
Unexpected sleeping behavior.

### ISSUE THREAD

**Issue by XvSkItZvX** [CreativeMD/OpticManager#4]
I have used the Optics Manager (1.1.3) to adjust day length (140708) and night length (106149) for a total day length of 246857, Which provides 7 day cycles in a real time 24hour period, or one week per day. 

I hadn't expected that beds would become usable at all times. It still appears to set time time to to 6:30am (or 6:40am) when used which I assume it still progresses the day.

I am currently testing this in SSP with the intent to use the finished pack on in SMP on a server. 

This behavior could become problematic in that environment, not to mention may possibly become abused when combined with mods that allow sleep to restore health.

I haven't came across anything stating that this is an intentional behavior or otherwise. However if it is I would like to request, if it's possible, the ability to disable this behavior.

Thanks in advance, and if there is any other information I can provide I will be happy to help.

Edit: Replaced the place holder for version of mod.

**Comment by CreativeMD** [comment]
So you would like to have a config option to disable sleeping, right?

**Comment by XvSkItZvX** [comment]
Not entirely, Just during the day.

**Comment by CreativeMD** [comment]
Sorry, that i have been rather inactive the last days. I'm pretty busy with working on LittleTiles at the moment.

The thing is that OpticManager doesn't change anything about that. Meaning you can sleep at the same time you can in vanilla Minecraft, but it might feel off to you since the day & night circle of minecraft is rather fast.

**Comment by CreativeMD** [comment]
If there is anything else to discuss just let me know and reopen the issue.
