### ISSUE TITLE
Moon Phase does not advance

### ISSUE THREAD

**Issue by Cyprex** [CreativeMD/OpticManager#7]
Moon Phase does not advance with OpticManager installed.
Possibly the same root cause as #6 
To reproduce:
Look at moon at night.
/time add 24000 repeatedly
Expected: Moon changes phase
Result: Moon doesn't change phase

**Comment by CreativeMD** [comment]
Will be fixed in v1.1.4 which should be available soon. Thanks for reporting this issue.
