### ISSUE TITLE
[1.1.4] Extra Utils 2 quantum quarry explode when night is made longer

### ISSUE THREAD

**Issue by Aphyxia** [CreativeMD/OpticManager#8]
Extra Utils 2 quantum quarry has an inbuilt mechanic that it is made to explode when it detects tampering with ticks, namely speeding up ticks via time acceleration wand or other mods. 
It seems that lengthening the NIGHT via OM also causes this.
Lengthening the day seems to be okay.

On single player setting it back to 12000 seems to fix it. Day length I had previously set to 30000 but changing it seems to have no effect.
On multi player quantum quarry seems to be permanently broken, no amount of changing day/night lengths seems to fix it. On the previous version (1.1.3?) and before night time change it was fine.

Edit: https://github.com/CreativeMD/OpticManager/issues/9 would explain why only night time is affecting the quarry.

Optic manager 1.1.4
Latest Extra utils 2 as of this date
MC 1.12.2
Forge 2601

**Comment by CreativeMD** [comment]
Does this update fix it?
https://www.dropbox.com/s/5wx6exgkghrxzt5/OpticManager%20v1.1.5%20mc1.12.2.jar?dl=1

**Comment by Aphyxia** [comment]
It seems to. At first I tested an already existing single player world and changing the night time produced this bug again. So I created a new world and found that there the bug didn't occur. Faced with a 50% chance I tried it on my server and it seemed to work there. Changing night or day length didn't cause the quantum quarry to overheat. So I guess you can consider it fixed?

**Comment by CreativeMD** [comment]
Nice! Good to hear that. Thanks for reporting this issue. Fix is already uploaded.
