### ISSUE TITLE
[v1.1.4 mc1.12.2] Night duration applied to day duration after day 2

### ISSUE THREAD

**Issue by Naxdar** [CreativeMD/OpticManager#9]
On a new world, I set the day duration to 48000 and the night to 18000, I noticed that the day was progressing faster than usual the second day. After testing, it seems the night duration is still used for every day/night coming after. It is obvious if you set the night duration to something crazy like 120.
Tested with no other mod on the v1.1.4 mc1.12.2 version.

**Comment by CreativeMD** [comment]
Does this update fix it?
https://www.dropbox.com/s/5wx6exgkghrxzt5/OpticManager%20v1.1.5%20mc1.12.2.jar?dl=1

**Comment by Naxdar** [comment]
I tested it and it seems to work fine now.

**Comment by CreativeMD** [comment]
Cool. Thanks for reporting this issue. Fix will be available for everyone soon.
